### ISSUE TITLE
EOF issues with resume on darwin

### ISSUE THREAD

**Issue by slingamn** [bitbot-irc/bitbot#59]
Summarizing investigation thus far:

* bitbot and darwin.network both support relatively recent versions of the draft/resume cap. (I just upgraded darwin to `draft/resume-0.5`, which technically [doesn't exist yet](https://github.com/DanielOaks/ircv3-specifications/pull/2), but the behavior changes shouldn't affect bitbot so you can just bump your own version number if you feel comfortable with that.)
* After repeated resumes against darwin.network, bitbot has a tendency to die with an EOF:

````
2019-05-30T15:47:09.220Z [ERROR] Failed to write to darwin
2019-05-30T15:47:09.220Z [CRITICAL] Unhandled exception: EOF occurred in violation of protocol (_ssl.c:2341)
Traceback (most recent call last):
  File "start.py", line 97, in <module>
    bot.run()
  File "/opt/bitbot/src/IRCBot.py", line 241, in run
    sock._send()
  File "/opt/bitbot/src/IRCServer.py", line 263, in _send
    lines = self.socket._send()
  File "/opt/bitbot/src/IRCSocket.py", line 135, in _send
    bytes_written_i = self._socket.send(self._write_buffer)
  File "/usr/lib/python3.7/ssl.py", line 984, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2341)
````

* The issue reproduces fairly easily against the production darwin.network (it seems to happen reliably after 3 or 4 consecutive resumes). strace from the server side (when connected to the default port 6697, which uses stunnel as the TLS terminator) looks like:

````
[pid 29616] 16:49:54.117934 writev(55, [{iov_base="@time=2019-05-30T20:49:54.117Z :irc.darwin.network 001 BitBot :Welcome to the Internet Relay Network BitBot\r\n", iov_len=109}, {iov_base="@time=2019-05-30T20:49:54.117Z :irc.darwin.network 002 BitBot :Your host is irc.darwin.network, running version oragono-1.1.0-unreleased\r\n", iov_len=138}, {iov_base="@time=2019-05-30T20:49:54.117Z :irc.darwin.network 003 BitBot :This server was created Mon, 27 May 2019 10:19:18 UTC\r\n", iov_len=118}, {iov_base="@time=2019-05-30T20:49:54.117Z :irc.darwin.network 004 BitBot irc.darwin.network oragono-1.1.0-unreleased BioRsE bEeIikmntRsl\r\n", iov_len=127}], 4) = 492
[redacted writes of registration burst lines]
[pid  2328] 16:49:54.122621 read(55, 0xc0003ae000, 7168) = -1 EAGAIN (Resource temporarily unavailable)
[redacted writes of registration burst lines]
[pid 29616] 16:49:54.123349 writev(20, [{iov_base=":BitBot!~BitBot@jesopo.uk JOIN #bitbot\r\n", iov_len=40}], 1) = 40
[pid  4712] 16:49:54.395443 read(55, "", 7168) = 0
[pid  4712] 16:49:54.395629 write(2, "\33[38;5;243m2019-05-30T20:49:54.395Z\33[0m \33[38;5;8m:\33[0m \33[38;5;117minfo\33[0m \33[38;5;8m:\33[0m \33[38;5;229mlocalconnect-ip\33[0m \33[38;5;8m:\33[0m disconnecting session of BitBot from 2a00:d880:5:3a:4::1\n", 193) = 193
[pid  4712] 16:49:54.395895 write(55, ":BitBot!~BitBot@jesopo.uk QUIT :connection closed\r\nERROR :connection closed\r\n", 77) = -1 EPIPE (Broken pipe)
[pid  4712] 16:49:54.395945 --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=29602, si_uid=112} ---
[pid  4712] 16:49:54.396061 close(55)   = 0
````

The important thing here is the `read(2)` call that returns 0; oragono is seeing an EOF as well as bitbot.

The issue also reproduces when bitbot is connected directly to a native TLS listener of oragono's, bypassing stunnel:

````
[pid 29615] 16:55:52.984143 write(56, "\27\3\3\0r\0\0\0\0\0\0\0\31\251\214\tq\332\250\336G\272`\1\20\372ll2\36\220\254w7M\31\t\302\343\243\342\244\302N\6I\262u\237\303\5\242h\217r\33N\343\325\0035\325x!\332zK\353\224\3729\313\332\317]\7\17x|KghZ\20\306\250Uz?zW\25\354\270\355\1f\t\2609|i\234dc\356\201\256\202\216\336\270\365\361\347\271\231\242\245", 119) = 119
[pid 29615] 16:55:52.984237 read(56, 0xc0003e0000, 2435) = -1 EAGAIN (Resource temporarily unavailable)
[redacted JOIN lines sent to other clients]
[pid  4712] 16:55:53.225746 read(56, 0xc0003e0000, 2435) = -1 ECONNRESET (Connection reset by peer)
[pid  4712] 16:55:53.225936 write(2, "\33[38;5;243m2019-05-30T20:55:53.225Z\33[0m \33[38;5;8m:\33[0m \33[38;5;117minfo\33[0m \33[38;5;8m:\33[0m \33[38;5;229mlocalconnect-ip\33[0m \33[38;5;8m:\33[0m disconnecting session of BitBot from 2a00:d880:5:3a:4::1\n", 193) = 193
[pid  4712] 16:55:53.226532 write(56, "\27\3\3\0e\0\0\0\0\0\0\0\32\250\261\347\352\3062\266\3\314\26\330(\332\205\263*N\227\217\312\260\313]0\35\277\362\362\226\265*\323\260\17\325\306\312\345\303\315?\274\272\341\232\342uT\257qo\206&R\202\2566\335\264\236\235\2\363<b\204{Bo\233\375\256\30y'\351\4_I\2249a%\263\3\355\251\225**\3102\276", 106) = -1 EPIPE (Broken pipe)
[pid  4712] 16:55:53.226664 --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=29602, si_uid=112} ---
[pid  4712] 16:55:53.226861 write(56, "\25\3\3\0\32\0\0\0\0\0\0\0\33\347\226\263\n\251\271\272\334H\3366\216\255\212\314\215[\370", 31) = -1 EPIPE (Broken pipe)
[pid  4712] 16:55:53.226983 --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=29602, si_uid=112} ---
[pid 29616] 16:55:53.227208 close(56)   = 0
````

Here, instead of `read(2)` returning 0, it fails and returns `ECONNRESET`, but the behavior is the same.

The issue appears *not* to reproduce when bitbot speaks plaintext to a client-side stunnel, which then speaks TLS to darwin.

**Comment by jesopo** [comment]
turns out BitBot tries to write 0 bytes to the socket just before this happens. that'll be the cause of this.

https://github.com/openssl/openssl/issues/6308

**Comment by jesopo** [comment]
easy solution would be to put an `else: return []` on this `if` statement https://github.com/jesopo/bitbot/blob/4698ea6f78d100185496290236b3e53a426f340c/src/IRCSocket.py#L126 but I'd prefer to figure out how `_send` is  being called when there's no space on the throttled write buffer.

**Comment by jesopo** [comment]
seems that, in every other scenario, `_write_buffer` and `_queued_lines` are completely empty by the time we turn on write throttling (on `RPL_WELCOME`) except when doing `RESUME` + SASL `AUTHENTICATE` - in which case we still have an `AUTHENTICATE` line stuck in `_queued_lines` when we get `RPL_WELCOME` because `RESUME` aborts `CAP` handshake.


Wowzer.
