### ISSUE TITLE
Error when trying to authenticate for first time with master pass

### ISSUE THREAD

**Issue by fosslinux** [bitbot-irc/bitbot#80]
I'm trying to authenticate for the first time with a masterpass. I've run the appropriate command and have the pass, but when I authenticate I don't get anything back from BitBot and this is spat out in the console:

```
2019-07-06T04:07:54.720Z [ERROR] failed to call event "received.message.private"
Traceback (most recent call last):
  File "/home/fosslinux/packages/bitbot-opers/src/EventManager.py", line 169, in _call
    returned = hook.call(event)
  File "/home/fosslinux/packages/bitbot-opers/src/EventManager.py", line 41, in call
    return self.function(event)
  File "/home/fosslinux/packages/bitbot-opers/modules/commands/__init__.py", line 333, in private_message
    args_split, event["tags"], hook, command_prefix="")
  File "/home/fosslinux/packages/bitbot-opers/modules/commands/__init__.py", line 189, in command
    command_method = self._command_method(target, server)
  File "/home/fosslinux/packages/bitbot-opers/modules/commands/__init__.py", line 92, in _command_method
    self.bot.set_setting(COMMAND_METHOD, "PRIVMSG"))).upper()
AttributeError: 'NoneType' object has no attribute 'upper'
```

What's going on here?

**Comment by jesopo** [comment]
closed by #81
