### ISSUE TITLE
timer.rss traceback

### ISSUE THREAD

**Issue by Mikaela** [bitbot-irc/bitbot#86]
```
Jul 08 16:17:19 relpda python3[8127]: 2019-07-08T16:17:19.753Z [ERROR] failed to call event "timer.rss"
Jul 08 16:17:19 relpda python3[8127]: Traceback (most recent call last):
Jul 08 16:17:19 relpda python3[8127]:   File "/home/bitbot/bitbot/src/EventManager.py", line 169, in _call
Jul 08 16:17:19 relpda python3[8127]:     returned = hook.call(event)
Jul 08 16:17:19 relpda python3[8127]:   File "/home/bitbot/bitbot/src/EventManager.py", line 41, in call
Jul 08 16:17:19 relpda python3[8127]:     return self.function(event)
Jul 08 16:17:19 relpda python3[8127]:   File "/home/bitbot/bitbot/modules/rss.py", line 46, in timer
Jul 08 16:17:19 relpda python3[8127]:     pages = utils.http.request_many(hooks.keys())
Jul 08 16:17:19 relpda python3[8127]:   File "/home/bitbot/bitbot/src/utils/http.py", line 135, in request_many
Jul 08 16:17:19 relpda python3[8127]:     loop.run_until_complete(task)
Jul 08 16:17:19 relpda python3[8127]:   File "/home/bitbot/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/asyncio/base_events.py", line 563, in run_until_complete
Jul 08 16:17:19 relpda python3[8127]:     future = tasks.ensure_future(future, loop=self)
Jul 08 16:17:19 relpda python3[8127]:   File "/home/bitbot/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/asyncio/tasks.py", line 587, in ensure_future
Jul 08 16:17:19 relpda python3[8127]:     raise ValueError('loop argument must agree with Future')
Jul 08 16:17:19 relpda python3[8127]: ValueError: loop argument must agree with Future
```

**Comment by jesopo** [comment]
fixed as of jesopo/bitbot@469c7256750ce4d508737fcb1031895b2edf60e5
